### ISSUE TITLE
plugin crash with Cannot create class (Phpstorm 2023.3.4, Ubuntu 22.04.3 LTS)

### ISSUE THREAD

**Issue by zoltansuto** [SimiaCryptus/intellij-aicoder#130]
phpstorm is installed via snap
Phpstorm 2023.3.4
Ubuntu 22.04.3 LTS
folder is writable (775) - there's a lib folder with the packages
plugin version: 1.2.22 - I don't know how I can upgrade to latest

I tried manually installing the latest but that fails with different issues

`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.generic.AnalogueFileAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1401)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1377)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1400)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1733)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:323)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:314)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:374)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:351)
	at com.github.simiacryptus.aicoder.ui.ProjectMenu.getChildren(ProjectMenu.kt:9)
	at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.doGetChildren(ActionUpdater.kt:706)
	at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.access$doGetChildren(ActionUpdater.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$getGroupChildren$2$children$1$1.invoke(ActionUpdater.kt:364)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$getGroupChildren$2$children$1$1.invoke(ActionUpdater.kt:363)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$3$adjustedCall$1.invoke(ActionUpdater.kt:157)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invokeSuspend(InternalReadAction.kt:36)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$3.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:35)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionUndispatched(coroutines.kt:82)
	at com.intellij.openapi.application.CoroutinesKt.readActionUndispatched(coroutines.kt:69)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.kt:740)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.kt:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.kt:363)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.iterateGroupChildren(ActionUpdater.kt:505)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.kt:412)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$expandGroupChild(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$doExpandActionGroup$2$result$1$1$1.invokeSuspend(ActionUpdater.kt:342)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ExceptionInInitializerError
	at org.codehaus.groovy.reflection.ClassInfo.isValidWeakMetaClass(ClassInfo.java:284)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassForClass(ClassInfo.java:254)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:310)
	at com.github.simiacryptus.aicoder.actions.generic.AnalogueFileAction.$getStaticMetaClass(AnalogueFileAction.groovy)
	at com.github.simiacryptus.aicoder.actions.generic.AnalogueFileAction.<init>(AnalogueFileAction.groovy:19)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1383)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1392)
	... 56 more
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 3.0.13 and you are trying to load version 3.0.19
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:81)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModulesFrom(ExtensionModuleScanner.java:63)
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:54)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:125)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37)
	... 63 more
`
and the same error appears for 11 more times
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.generic.CreateFileAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.ImplementStubAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.DocAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.CommentsAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.DescribeAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.InsertImplementationAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.PasteAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.RecentCodeEditsAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.code.CustomEditAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.markdown.MarkdownImplementActionGroup (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.generic.AppendAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`
`com.intellij.diagnostic.PluginException: Cannot create class com.github.simiacryptus.aicoder.actions.generic.ReplaceOptionsAction (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AI Coding Assistant, id=com.github.simiacryptus.intellijopenaicodeassist, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PhpStorm2023.3/intellij-aicoder, version=1.2.22, package=null, isBundled=false), packagePrefix=null, state=active))`

**Comment by Fjf** [comment]
I have the same issue, same Ubuntu but latest PyCharm (2024.2.3).
