### ISSUE TITLE
Error no Found

### ISSUE THREAD

**Issue by OmarSanch** [SimiaCryptus/intellij-aicoder#152]
Log Message: Error running task
Error Message: null
Error Type: java.lang.reflect.UndeclaredThrowableException
API Base: https://api.openai.com/v1
Token Counter: 0

OS: Mac OS X / 14.4.1 / aarch64
Locale: 419 / es

Error Details:
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy7/jdk.proxy7.$Proxy324.suggestText(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:203)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at com.github.simiacryptus.aicoder.actions.generic.ReplaceOptionsAction$_processSelection_closure1.doCall(ReplaceOptionsAction.groovy:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
	at jdk.proxy2/jdk.proxy2.$Proxy323.invoke(Unknown Source)
	at com.github.simiacryptus.aicoder.util.UITools$BgTask.run(UITools.kt:715)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.simiacryptus.util.HttpClientManager.withPool(HttpClientManager.kt:94)
	at com.simiacryptus.util.HttpClientManager.withTimeout(HttpClientManager.kt:181)
	at com.simiacryptus.util.HttpClientManager$withReliability$1.invoke(HttpClientManager.kt:188)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:101)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:96)
	at com.simiacryptus.util.HttpClientManager.withReliability(HttpClientManager.kt:188)
	at com.simiacryptus.util.HttpClientManager.withReliability$default(HttpClientManager.kt:187)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:434)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:93)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:75)
	... 45 more
Caused by: java.lang.RuntimeException: java.io.IOException: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:458)
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:435)
	at com.simiacryptus.util.HttpClientManager.withPerformanceLogging(HttpClientManager.kt:193)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:435)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:434)
	at com.simiacryptus.util.HttpClientManager$withTimeout$1.invoke(HttpClientManager.kt:181)
	at com.simiacryptus.util.HttpClientManager.withPool$lambda$0(HttpClientManager.kt:93)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.IOException: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
	... 13 more

```

Action History:

* Action: DescribeAction
* Action: CodeChatAction
* Action: ReplaceOptionsAction

Error History:

Error running task
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy7/jdk.proxy7.$Proxy322.describeCode(Unknown Source)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction$DescribeAction_VirtualAPI$describeCode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction.processSelection(DescribeAction.groovy:49)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction.processSelection(DescribeAction.groovy)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:193)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:192)
	at com.github.simiacryptus.aicoder.util.UITools$BgTask.run(UITools.kt:715)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:112)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:96)
	at com.simiacryptus.util.HttpClientManager.withReliability(HttpClientManager.kt:188)
	at com.simiacryptus.util.HttpClientManager.withReliability$default(HttpClientManager.kt:187)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:434)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:93)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:75)
	... 30 more

```

Error
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy7/jdk.proxy7.$Proxy322.describeCode(Unknown Source)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction$DescribeAction_VirtualAPI$describeCode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction.processSelection(DescribeAction.groovy:49)
	at com.github.simiacryptus.aicoder.actions.code.DescribeAction.processSelection(DescribeAction.groovy)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:193)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:192)
	at com.github.simiacryptus.aicoder.util.UITools$BgTask.run(UITools.kt:715)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:112)
	at com.simiacryptus.util.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:96)
	at com.simiacryptus.util.HttpClientManager.withReliability(HttpClientManager.kt:188)
	at com.simiacryptus.util.HttpClientManager.withReliability$default(HttpClientManager.kt:187)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:434)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:93)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:75)
	... 30 more
![error2](https://github.com/SimiaCryptus/intellij-aicoder/assets/87913476/e4c3186b-4c48-41fd-a61d-41a27e603695)

**Comment by acharneski** [comment]
Fixed, and improved error message for "You exceeded your current quota, please check your plan and billing details"
