### ISSUE TITLE
java.util.NoSuchElementException: Collection is empty.

### ISSUE THREAD

**Issue by RangareddyJulakanti** [SimiaCryptus/intellij-aicoder#162]
Log Message: Error
Error Message: Collection is empty.
Error Type: java.util.NoSuchElementException
API Base: {}

OS: Windows 11 / 10.0 / amd64
Locale: IN / en

Error Details:
```
java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201)
	at com.github.simiacryptus.aicoder.util.UITools.checkApiKey$default(UITools.kt:744)
	at com.github.simiacryptus.aicoder.util.UITools.run(UITools.kt:733)
	at com.github.simiacryptus.aicoder.util.UITools.run$default(UITools.kt:725)
	at com.github.simiacryptus.aicoder.actions.SelectionAction.processSelection(SelectionAction.kt:193)
	at com.github.simiacryptus.aicoder.actions.SelectionAction.handle$lambda$3(SelectionAction.kt:69)
	at com.github.simiacryptus.aicoder.util.UITools.redoableTask$lambda$2(UITools.kt:91)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by acharneski** [comment]
Thank you for the report! This has been fixed for next release. This error will occur if no API keys are configured. To solve, you can go into settings -> tools -> AI Coder, and then enter your API key(s.
