### ISSUE TITLE
Error when running every action /except/ chat

### ISSUE THREAD

**Issue by AsafMah** [SimiaCryptus/intellij-aicoder#68]
For all actions, I'm getting this api log:

[DEBUG] [3680.219] Request failed; retrying (1/3): java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null
[DEBUG] [3690.542] Request completed in 307ms
[DEBUG] [3690.542] Request failed; retrying (2/3): java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null

For chat, it does work:

[INFO] [3524.928] Chat Request
		Prefix:
			{
			  "messages" : [ {
			    "role" : "system",
			    "content" : "Append text to the end of the user's prompt"
			  }, {
			    "role" : "user",
			    "content" : "mod arrow;\nmod authorization_policy;\npub mod client;\npub mod client_details;\npub mod cloud_info;\npub mod connection_string;\npub mod credentials;\npub mod error;\npub mod models;\nmod operations;\npub mod prelude;\npub mod request_opti"
			  } ],
			  "model" : "gpt-4",
			  "temperature" : 0.47,
			  "max_tokens" : 8192
			}
[INFO] [3526.635] Chat Completion:
			ons;
			pub mod response;
			mod service;
			mod util;
			mod version;

I am using 1.22

**Comment by acharneski** [comment]
Thanks for the report. The version # is invalid... I assume you mean 1.2.0, the current release?
Is there any sort of stack trace you can see? This doesn't sound like a known issue. However, I do have a new version awaiting approval that has a number of fixes

**Comment by AsafMah** [comment]
I tried 1.2.0, and then 1.2.2 from this github.

I don't see any more error details in the api window

**Comment by acharneski** [comment]
Hard to tell without the stack, which is likely found in the intellij error log, but I'd suggest you double-check your API Base setting. Nearly all features end up using "chat" so that isn't very informative. Are you trying to process anything unusual, like non-latin characters?

**Comment by AsafMah** [comment]
Some logs from the latest update:

```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy3/jdk.proxy3.$Proxy380.suggestRenames(Unknown Source)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction$handle$1$renameSuggestions$1.invoke(RenameVariablesAction.kt:61)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction$handle$1$renameSuggestions$1.invoke(RenameVariablesAction.kt:58)
	at com.github.simiacryptus.aicoder.util.UITools.run1(UITools.kt:829)
	at com.github.simiacryptus.aicoder.util.UITools.run(UITools.kt:815)
	at com.github.simiacryptus.aicoder.util.UITools.run$default(UITools.kt:807)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction.handle$lambda$3(RenameVariablesAction.kt:58)
	at com.github.simiacryptus.aicoder.util.UITools.redoableTask$lambda$0(UITools.kt:71)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.simiacryptus.openai.HttpClientManager.runAsync(HttpClientManager.kt:168)
	at com.simiacryptus.openai.HttpClientManager.withCancellationMonitor(HttpClientManager.kt:115)
	at com.simiacryptus.openai.HttpClientManager.withCancellationMonitor(HttpClientManager.kt:100)
	at com.simiacryptus.openai.HttpClientManager$withReliability$1$1.invoke(HttpClientManager.kt:179)
	at com.simiacryptus.openai.HttpClientManager.withTimeout(HttpClientManager.kt:136)
	at com.simiacryptus.openai.HttpClientManager$withReliability$1.invoke(HttpClientManager.kt:178)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:55)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:51)
	at com.simiacryptus.openai.HttpClientManager.withReliability(HttpClientManager.kt:177)
	at com.simiacryptus.openai.HttpClientManager.withReliability$default(HttpClientManager.kt:176)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:422)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:91)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:65)
	... 14 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:446)
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:423)
	at com.simiacryptus.openai.HttpClientManager.withPerformanceLogging(HttpClientManager.kt:186)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:423)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:422)
	at com.simiacryptus.openai.HttpClientManager.runAsync$lambda$7(HttpClientManager.kt:158)
	... 6 more
```

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[API Thread 2,5,main] 393796765 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 668728885
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:424)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:224)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:212)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getText(ASTDelegatePsiElement.java:144)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction$handle$1$renameSuggestions$1.invoke(RenameVariablesAction.kt:62)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction$handle$1$renameSuggestions$1.invoke(RenameVariablesAction.kt:58)
	at com.github.simiacryptus.aicoder.util.UITools.run1(UITools.kt:829)
	at com.github.simiacryptus.aicoder.util.UITools.run(UITools.kt:815)
	at com.github.simiacryptus.aicoder.util.UITools.run$default(UITools.kt:807)
	at com.github.simiacryptus.aicoder.actions.code.RenameVariablesAction.handle$lambda$3(RenameVariablesAction.kt:58)
	at com.github.simiacryptus.aicoder.util.UITools.redoableTask$lambda$0(UITools.kt:71)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy3/jdk.proxy3.$Proxy389.editCode(Unknown Source)
	at com.github.simiacryptus.aicoder.actions.code.CommentsAction$CommentsAction_VirtualAPI$editCode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
	at com.github.simiacryptus.aicoder.actions.code.CommentsAction.processSelection(CommentsAction.groovy:25)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:50)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:49)
	at com.github.simiacryptus.aicoder.util.UITools.run1(UITools.kt:829)
	at com.github.simiacryptus.aicoder.util.UITools.run(UITools.kt:815)
	at com.github.simiacryptus.aicoder.util.UITools.run$default(UITools.kt:807)
	at com.github.simiacryptus.aicoder.actions.SelectionAction.handle$lambda$0(SelectionAction.kt:49)
	at com.github.simiacryptus.aicoder.util.UITools.redoableTask$lambda$0(UITools.kt:71)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.simiacryptus.openai.HttpClientManager.runAsync(HttpClientManager.kt:168)
	at com.simiacryptus.openai.HttpClientManager.withCancellationMonitor(HttpClientManager.kt:115)
	at com.simiacryptus.openai.HttpClientManager.withCancellationMonitor(HttpClientManager.kt:100)
	at com.simiacryptus.openai.HttpClientManager$withReliability$1$1.invoke(HttpClientManager.kt:179)
	at com.simiacryptus.openai.HttpClientManager.withTimeout(HttpClientManager.kt:136)
	at com.simiacryptus.openai.HttpClientManager$withReliability$1.invoke(HttpClientManager.kt:178)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:55)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:51)
	at com.simiacryptus.openai.HttpClientManager.withReliability(HttpClientManager.kt:177)
	at com.simiacryptus.openai.HttpClientManager.withReliability$default(HttpClientManager.kt:176)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:422)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:91)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:65)
	... 19 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "jsonObject" is null
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:446)
	at com.simiacryptus.openai.OpenAIClient$moderate$1$1.invoke(OpenAIClient.kt:423)
	at com.simiacryptus.openai.HttpClientManager.withPerformanceLogging(HttpClientManager.kt:186)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:423)
	at com.simiacryptus.openai.OpenAIClient$moderate$1.invoke(OpenAIClient.kt:422)
	at com.simiacryptus.openai.HttpClientManager.runAsync$lambda$7(HttpClientManager.kt:158)
	... 6 more

```

**Comment by acharneski** [comment]
Thank you! I added a workaround and it is out with 1.2.4 - I have no idea why the moderation endpoint was giving an empty response! Closing ticket. Thanks for the report!
