### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by biscuit314** [SimiaCryptus/intellij-aicoder#70]
I'm sure I'm just doing something wrong.  There are positive reviews and blog posts.

However, not one action results in success

Plugin version:       AI Coding Assistant 1.2.3
PyCharm version:  2023.1.4

When I highlight text, right-click, then choose any selection from the AI Coder submenu, a progress bar titled with the choice I made appears, instantly showing 100% but it stays there frozen.  Occassionally (e.g. with "Ask question about the code" an additional dialog appears behind the progress dialog)
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/8892155/04b3309d-13f3-4179-953e-2ed72be37545)

I get a similar stack traces with the following (implement stub copy/pasted below)
* Implement stub
* Paste
* Add Doc Comments
* Rename Variables
* Add Code comments
* Describe Code and Prepend Comments
* Replace Options
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy3/jdk.proxy3.$Proxy260.editCode(Unknown Source)
	at com.github.simiacryptus.aicoder.actions.code.ImplementStubAction$VirtualAPI$editCode.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
	at com.github.simiacryptus.aicoder.actions.code.ImplementStubAction.processSelection(ImplementStubAction.groovy:71)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:51)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:50)
	at com.github.simiacryptus.aicoder.util.UITools$run2$1.compute(UITools.kt:852)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:353)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry(HttpClientManager.kt:65)
	at com.simiacryptus.openai.HttpClientManager.withExpBackoffRetry$default(HttpClientManager.kt:51)
	at com.simiacryptus.openai.HttpClientManager.withReliability(HttpClientManager.kt:177)
	at com.simiacryptus.openai.HttpClientManager.withReliability$default(HttpClientManager.kt:176)
	at com.simiacryptus.openai.OpenAIClient.moderate(OpenAIClient.kt:422)
	at com.simiacryptus.openai.proxy.ChatProxy.complete(ChatProxy.kt:91)
	at com.simiacryptus.openai.proxy.GPTProxyBase.create$lambda$5(GPTProxyBase.kt:65)
	... 31 more
```

Each of the other menu items has a slightly different result - none of which are successful.  For example, the stack trace for "Ask a question about the code" produces:
```
java.lang.NullPointerException: Cannot invoke method isBlank() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at com.github.simiacryptus.aicoder.actions.code.QuestionAction.processSelection(QuestionAction.groovy:37)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:51)
	at com.github.simiacryptus.aicoder.actions.SelectionAction$handle$1$newText$1.invoke(SelectionAction.kt:50)
	at com.github.simiacryptus.aicoder.util.UITools$run2$1.compute(UITools.kt:852)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:353)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:513)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

What am I doing wrong?

**Comment by acharneski** [comment]
I'll be honest... I recently broke several actions including this one. The fix should be out on Monday.  Sorry about that!

**Comment by acharneski** [comment]
BTW Thank you very much for your thorough bug report! It isn't as easy as it sounds to keep all these toys working when you make a major change!

**Comment by biscuit314** [comment]
Been there!  Thanks for your rapid reply :-)  Looking forward to the fix

**Comment by acharneski** [comment]
1.2.4 is release and should be approved by Jetbrains tomorrow. You can also install it youself from the "releases" here but keep in mind that will take you off the automatically updated plugin verson. Close this ticket. thanks again for the report!
