### ISSUE TITLE
Error when asking a question about code

### ISSUE THREAD

**Issue by parviain** [SimiaCryptus/intellij-aicoder#96]
```
2023-10-09 10:18:59,323 [1397134]   INFO - STDOUT - 10:18:59.323 [API Thread 4] DEBUG com.simiacryptus.openai.HttpClientManager -- Request completed in 2173ms
2023-10-09 10:18:59,323 [1397134]   INFO - STDOUT - 10:18:59.323 [API Thread 4] INFO com.simiacryptus.openai.HttpClientManager -- Async request completed; isDone 1162707798 released
2023-10-09 10:18:59,323 [1397134]   INFO - STDOUT - 10:18:59.323 [ApplicationImpl pooled thread 35] INFO com.simiacryptus.openai.HttpClientManager -- Async request completed; getting value
2023-10-09 10:18:59,323 [1397134]   INFO - STDOUT - 10:18:59.323 [ApplicationImpl pooled thread 35] INFO com.simiacryptus.openai.HttpClientManager -- Async request completed; got value
2023-10-09 10:18:59,323 [1397134]   INFO - STDOUT - 10:18:59.323 [ApplicationImpl pooled thread 35] INFO com.simiacryptus.openai.HttpClientManager -- Async request completed
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 10:18:59.329 [ApplicationImpl pooled thread 35] ERROR com.github.simiacryptus.aicoder.util.UITools -- Error running task
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - java.lang.NullPointerException: Cannot invoke method withIndent() on null object
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.code.QuestionAction.processSelection(QuestionAction.groovy:59)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.code.QuestionAction.processSelection(QuestionAction.groovy)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:192)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:191)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at 
```com.github.simiacryptus.aicoder.util.UITools$BgTask.run(UITools.kt:862)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
2023-10-09 10:18:59,329 [1397140]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-10-09 10:18:59,330 [1397141]   INFO - STDOUT - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 10:18:59.332 [API Thread 3] ERROR com.github.simiacryptus.aicoder.util.UITools -- Error
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - java.lang.NullPointerException: Cannot invoke method withIndent() on null object
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.code.QuestionAction.processSelection(QuestionAction.groovy:59)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.code.QuestionAction.processSelection(QuestionAction.groovy)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:192)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.actions.SelectionAction$processSelection$1.invoke(SelectionAction.kt:191)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.github.simiacryptus.aicoder.util.UITools$BgTask.run(UITools.kt:862)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
2023-10-09 10:18:59,332 [1397143]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2023-10-09 10:18:59,333 [1397144]   INFO - STDOUT - 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by acharneski** [comment]
Thanks for the report! This should be fixed in the next release (not the one that will be released on Monday; the next code release)
